# Generated by Django 4.1.7 on 2023-04-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'Petite annonce', 'verbose_name_plural': 'Petites annonces'},
        ),
    ]
