# Generated by Django 4.1.7 on 2023-03-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='main_activity_perdiod',
            new_name='main_activity_period',
        ),
    ]
