# Generated by Django 4.1.7 on 2023-04-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amphibian',
            name='call_volume',
            field=models.CharField(blank=True, choices=[('A', 'Aphone'), ('D', 'Discret'), ('F', 'Bruyant')], max_length=1, verbose_name='Volume du champs'),
        ),
        migrations.AlterField(
            model_name='amphibian',
            name='detention_difficulty',
            field=models.CharField(choices=[('S', 'Pour éleveur débutant (premier amphibien)'), ('E', 'Pour éleveur ayant déjà une base'), ('H', 'Pour éleveur expérimenté'), ('V', 'Pour éleveur très expérimenté')], help_text="Pour maintenir l'espèce ou la manipuler", max_length=1, verbose_name='Difficulté de maintien'),
        ),
    ]
