# Generated by Django 4.1.7 on 2023-03-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_rename_main_activity_perdiod_card_main_activity_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='venom',
        ),
        migrations.AddField(
            model_name='card',
            name='venom',
            field=models.ManyToManyField(blank=True, to='card.venom'),
        ),
    ]
