# Generated by Django 4.1.7 on 2023-04-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_amphibian_call_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amphibian',
            name='adult_female_size',
            field=models.PositiveIntegerField(help_text='en mm', verbose_name='Taille adulte femelle'),
        ),
        migrations.AlterField(
            model_name='amphibian',
            name='adult_male_size',
            field=models.PositiveIntegerField(help_text='en mm', verbose_name='Taille adulte mâle'),
        ),
    ]
