# Generated by Django 4.1.7 on 2023-04-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_amphibian_adult_female_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amphibian',
            name='main_mores',
            field=models.CharField(choices=[('W', 'Aquatique'), ('B', 'Fouisseur'), ('T', 'Terrestre'), ('A', 'Arboricole')], help_text='Moeurs', max_length=1, verbose_name='Moeurs'),
        ),
    ]
