# Generated by Django 4.1.7 on 2023-03-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_remove_card_venom_card_venom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_venomous',
        ),
    ]
