# Generated by Django 4.1.7 on 2023-03-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_remove_card_is_venomous'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='minimal_vivarium_size',
            field=models.CharField(default='', help_text='LxlxH', max_length=64),
            preserve_default=False,
        ),
    ]
