# Generated by Django 4.1.7 on 2023-04-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_amphibian_main_mores'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmphibianLifeCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom')),
            ],
        ),
        migrations.RemoveField(
            model_name='amphibian',
            name='can_live_in_group',
        ),
        migrations.AddField(
            model_name='amphibian',
            name='life_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='card.amphibianlifecommunity', verbose_name='Peut vivre en communauté'),
        ),
    ]
