# Generated by Django 4.1.7 on 2023-03-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_card_minimal_vivarium_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='adult_female_size',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='adult_male_size',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='born_size',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
