# Generated by Django 4.1.7 on 2023-03-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_card_adult_female_size_card_adult_male_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='lower_humidity',
        ),
        migrations.RemoveField(
            model_name='card',
            name='lower_temperature',
        ),
        migrations.RemoveField(
            model_name='card',
            name='max_humidity',
        ),
        migrations.RemoveField(
            model_name='card',
            name='max_temperature',
        ),
        migrations.AddField(
            model_name='card',
            name='humidity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='temperature',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
