# Generated by Django 4.1.7 on 2023-04-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_lizard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lizard',
            options={'verbose_name': 'Lézard', 'verbose_name_plural': 'Lézards'},
        ),
        migrations.AlterField(
            model_name='lizard',
            name='adult_female_size',
            field=models.PositiveIntegerField(help_text='en cm', verbose_name='Taille adulte de la femelle (SVL)'),
        ),
        migrations.AlterField(
            model_name='lizard',
            name='adult_male_size',
            field=models.PositiveIntegerField(help_text='en cm', verbose_name='Taille adulte du mâle (SVL)'),
        ),
    ]
