# Generated by Django 4.1.7 on 2023-03-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_remove_card_lower_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='venom',
            field=models.ManyToManyField(to='card.venom'),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='comments',
            field=models.TextField(blank=True, help_text='mutation, morphotype, hibridation'),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='locality',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='phase',
            field=models.CharField(blank=True, choices=[('J', 'Juvenil'), ('S', 'Sub adult'), ('A', 'Adult')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='sex',
            field=models.CharField(blank=True, choices=[('U', 'Undefined'), ('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
