# Generated by Django 4.1.7 on 2023-04-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_alter_lizard_options_alter_lizard_adult_female_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lizard',
            name='prehensile_tail',
        ),
        migrations.RemoveField(
            model_name='lizard',
            name='venom',
        ),
        migrations.RemoveField(
            model_name='lizard',
            name='venom_risks',
        ),
        migrations.AlterField(
            model_name='lizard',
            name='detention_difficulty',
            field=models.CharField(choices=[('S', 'Pour éleveur débutant (premier lézard)'), ('E', 'Pour éleveur ayant déjà une base'), ('H', 'Pour éleveur expérimenté'), ('V', 'Pour éleveur très expérimenté')], help_text="Pour maintenir l'espèce ou la manipuler", max_length=1, verbose_name='Difficulté de maintien'),
        ),
        migrations.AlterField(
            model_name='lizard',
            name='main_mores',
            field=models.CharField(choices=[('B', 'Fouisseur'), ('T', 'Terrestre'), ('A', 'Arboricole')], help_text='Moeurs', max_length=1, verbose_name='Moeurs'),
        ),
    ]
