# Generated by Django 4.1.7 on 2023-03-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_card_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bern_convention',
            field=models.CharField(choices=[('A', 'Annex I'), ('B', 'Annex II'), ('C', 'Annex III')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
