# Generated by Django 4.1.7 on 2023-04-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_remove_lizard_prehensile_tail_remove_lizard_venom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lizard',
            name='female_tail_size',
            field=models.PositiveIntegerField(help_text='en cm', verbose_name='Taille de la queue de la femelle'),
        ),
        migrations.AlterField(
            model_name='lizard',
            name='male_tail_size',
            field=models.PositiveIntegerField(help_text='en cm', verbose_name='Taille de la queue du mâle'),
        ),
    ]
