# Generated by Django 4.1.7 on 2023-03-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_card_bern_convention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='detention_difficulty',
            field=models.CharField(choices=[('S', 'Very easy'), ('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('V', 'Very hard')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='preys',
            field=models.ManyToManyField(to='card.prey'),
        ),
    ]
