# Generated by Django 4.1.7 on 2023-03-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='environments',
            field=models.ManyToManyField(to='card.environment'),
        ),
    ]
