# Generated by Django 4.1.7 on 2023-03-19 15:04

import card.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_alter_cardimage_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Espèce', 'verbose_name_plural': 'Espèces'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Famille', 'verbose_name_plural': 'Familles'},
        ),
        migrations.AlterModelOptions(
            name='environment',
            options={'verbose_name': 'Environnement', 'verbose_name_plural': 'Environnements'},
        ),
        migrations.AlterModelOptions(
            name='prey',
            options={'verbose_name': 'Proie', 'verbose_name_plural': 'Proies'},
        ),
        migrations.AlterModelOptions(
            name='venom',
            options={'verbose_name': 'Toxicologie', 'verbose_name_plural': 'Toxicologies'},
        ),
        migrations.RemoveField(
            model_name='prey',
            name='icon',
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default='', upload_to=card.models.card_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='adult_female_size',
            field=models.CharField(max_length=64, verbose_name='Taille adulte femelle'),
        ),
        migrations.AlterField(
            model_name='card',
            name='adult_male_size',
            field=models.CharField(max_length=64, verbose_name='Taille adulte mâle'),
        ),
        migrations.AlterField(
            model_name='card',
            name='bern_convention',
            field=models.CharField(choices=[('A', 'Annexe I'), ('B', 'Annexe II'), ('C', 'Annexe III')], max_length=1, verbose_name='Convention de Berne'),
        ),
        migrations.AlterField(
            model_name='card',
            name='born_size',
            field=models.CharField(max_length=64, verbose_name='Taille des juvéniles'),
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.category', verbose_name='Famille'),
        ),
        migrations.AlterField(
            model_name='card',
            name='comments',
            field=models.TextField(verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='card',
            name='detention_difficulty',
            field=models.CharField(choices=[('S', 'Très facile'), ('E', 'Facile'), ('M', 'Moyen'), ('H', 'Difficile'), ('V', 'Très difficile')], max_length=1, verbose_name='Difficulté de maintien'),
        ),
        migrations.AlterField(
            model_name='card',
            name='environments',
            field=models.ManyToManyField(to='card.environment', verbose_name='Environnements'),
        ),
        migrations.AlterField(
            model_name='card',
            name='genus',
            field=models.CharField(max_length=64, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='card',
            name='humidity',
            field=models.PositiveIntegerField(verbose_name='Humidité'),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_cites',
            field=models.BooleanField(verbose_name='Enregistré au CITES'),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_poisonous',
            field=models.BooleanField(verbose_name='Est vénéneux'),
        ),
        migrations.AlterField(
            model_name='card',
            name='main_activity_period',
            field=models.CharField(choices=[('N', 'Nocturne'), ('T', 'Crépusculaire'), ('D', 'Diurne')], max_length=1, verbose_name="Période d'activité"),
        ),
        migrations.AlterField(
            model_name='card',
            name='main_mores',
            field=models.CharField(choices=[('B', 'Fouisseur'), ('T', 'Terrestre'), ('A', 'Arboricole')], max_length=1, verbose_name='Moeurs'),
        ),
        migrations.AlterField(
            model_name='card',
            name='minimal_vivarium_size',
            field=models.CharField(help_text='LxlxH', max_length=64, verbose_name='Dimension minimal du terrarium'),
        ),
        migrations.AlterField(
            model_name='card',
            name='preys',
            field=models.ManyToManyField(to='card.prey', verbose_name='Proies'),
        ),
        migrations.AlterField(
            model_name='card',
            name='reproduction_type',
            field=models.CharField(choices=[('O', 'Ovipare'), ('V', 'Vivipare'), ('I', 'Ovovivipare')], max_length=1, verbose_name='Type de reproduction'),
        ),
        migrations.AlterField(
            model_name='card',
            name='species',
            field=models.CharField(max_length=64, verbose_name='Espèce'),
        ),
        migrations.AlterField(
            model_name='card',
            name='temperature',
            field=models.PositiveIntegerField(verbose_name='Température'),
        ),
        migrations.AlterField(
            model_name='card',
            name='venom',
            field=models.ManyToManyField(to='card.venom', verbose_name='Est venimeux'),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.card', verbose_name='Espèce'),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='comments',
            field=models.TextField(blank=True, help_text='mutation, morphotype, hybridation', verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='locality',
            field=models.CharField(blank=True, max_length=512, verbose_name='Localité'),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='phase',
            field=models.CharField(blank=True, choices=[('J', 'Juvénile'), ('S', 'Sub-adulte'), ('A', 'Adulte')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='sex',
            field=models.CharField(blank=True, choices=[('U', 'Indéfini'), ('M', 'Male'), ('F', 'Femelle')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='prey',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='venom',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nom'),
        ),
    ]
